classdef SourceDistribution < uix.VBoxFlex
% show the current source density (for silicon probe) or topoplot (for eeg
% data) estimation from the selected data in NeuroPlot
% for current source density, using kCSD toolbox;
% for topoplot, using EEGlab toolbox;
% modified from deepseek
properties
    Neuroresult;
    listener;
    Toolbar;
    ChannelPosition;
    Parameters;
    Data;
    dataXaxis;
    dataYaxis;
    ChannelType;
    figurepanel;
    Source;
end
properties(Constant)
     DEFAULT_CSD_PARAMS = struct(...
            'src_type', 'gauss', ...      % 基函数类型: 'gauss', 'step', 'gauss_lim'
            'sigma', 1, ...              % 电导率 (S/m)
            'h', 1, ...                 % 组织切片厚度 (mm)
            'n_src_init', 300, ...         % 初始源数量
            'R_init', 0.23, ...              % 基函数初始宽度 (mm)
            'lambd',0, ...              % 正则化参数
            'ext_x', 0.0, ...                 % X方向扩展 (mm)
            'ext_y', 0.0, ...                 % Y方向扩展 (mm)
            'gdx', 0.01, ...                  % X方向网格密度 (mm)
            'gdy', 0.01, ...                  % Y方向网格密度 (mm)
            'dist_table_density', 20, ...     % 距离表密度
            'MoI_iters', 20, ...               % Method of Images迭代次数
            'sigma_S', 5.0, ...                % 生理盐水电导率 (S/m)
            'cross_validate', false, ...       % 是否进行交叉验证
            'l_curve', false, ...              % 是否使用L-curve
            'xmin', [], ...                     % X最小边界 (自动计算)
            'xmax', [], ...                     % X最大边界 (自动计算)
            'ymin', [], ...                     % Y最小边界 (自动计算)
            'ymax', [] ...                       % Y最大边界 (自动计算)
        );
        
        DEFAULT_EEG_PARAMS = struct(...
            'plotrad', 0.6, ...      % 绘图半径
            'headrad', 0.5, ...      % 头部半径
            'intrad', 0.5, ...       % 插值半径
            'gridscale', 67, ...     % 网格缩放
            'shading', 'flat', ... % 着色方式
            'numcontour', 6, ...     % 等高线数量
            'colormap', 'jet', ...   % 颜色图
            'contourlines', 10, ...  % 等高线数量
            'electrodes', 'on', ...  % 显示电极
            'style', 'both',...      % 绘图样式
            'headmode','human'...    % 
        ); % used in topoplot for EEG.
end
methods(Access=public)
     function createToolbar(obj)
            if ~isempty(obj.Toolbar) && ishandle(obj.Toolbar)
                delete(obj.Toolbar);
            end
            obj.Toolbar = uix.HBox('Parent', obj);
            switch obj.ChannelType
                case 'EEG'
                uicontrol(obj.Toolbar,"Style","pushbutton","String",'setTopoplotParameter','Callback',@(~,~) obj.openEEGParameters());
                uicontrol(obj.Toolbar,'Style','pushbutton','String','CalculateTopoplot','Callback',obj.calculateSourceDistribution);
                case 'CSD'
                uicontrol(obj.Toolbar,"Style","pushbutton","String",'setCSDParameter','Callback',@(~,~) obj.openCSDParameters());
                uicontrol(obj.Toolbar,'Style','pushbutton','String','CalculateTopoplot','Callback',@(~,~) obj.calculateSourceDistribution);
            end
     end
     function createDataLoadPanel(obj)
            global currentresult
            validdatatype={'LFPdata','Spectrogram','TimeVaringConnectivity','PowerSpectralDensity','Connectivity'};
            datatypelist=[];
            for i=1:length(validdatatype)
                if isprop(currentresult,validdatatype{i})
                datatypelist=cat(1,datatypelist,validdatatype(i));
                end
            end
            if ~isempty(datatypelist)
            uicontrol(obj,"Tag",'Datatype',"Style","popupmenu","String",datatypelist,'Callback',@(~,~) obj.ChooseDatatype);
            else
                error('No support data to calculate source distribution');
            end
     end
     function ChooseDatatype(obj)
         global currentresult
         datatype=findobj(obj,'Tag','Datatype');
         datatype=datatype.String{datatype.Value};
         axisdefine=obj.Toolbar;
         delete(findobj(axisdefine,'style','text'));
         delete(findobj(axisdefine,'style','edit'));
         switch datatype
             case 'LFPdata'
                 uicontrol(axisdefine,"Style",'text','String','time range');
                 uicontrol(axisdefine,'Style','edit','Tag','dataXlim');
                 obj.LoadData('LFPdata');
             case 'Spectrogram'
                 uicontrol(axisdefine,"Style",'text','String','time range');
                 uicontrol(axisdefine,'Style','edit','Tag','dataXlim');
                 uicontrol(axisdefine,"Style",'text','String','frequency range');
                 uicontrol(axisdefine,'Style','edit','Tag','dataYlim');
                 obj.LoadData('Specdata');
                 % further data type are not working!
         end
     end
     function LoadData(obj,option)
         global currentresult
         switch option
             case 'LFPdata'
                obj.Data=currentresult.get('LFPdataplot');
                obj.dataXaxis=currentresult.get('t_lfpplot');
                tmp=findobj('Tag','dataXlim');
                tmp.String=num2str([min(obj.dataXaxis),max(obj.dataXaxis)]);
                obj.dataYaxis=[];
                ChannelPositionindex=currentresult.get('channelindexplot');
             case 'Specdata'
                obj.Data=currentresult.Spectrogram.get('Specdataplot');
                obj.dataXaxis=currentresult.Spectrogram.get('t_lfpplot');
                obj.dataYaxis=currentresult.Spectrogram.get('f_lfpplot');
                tmp=findobj('Tag','dataXlim');
                tmp.String=num2str([min(obj.dataXaxis),max(obj.dataXaxis)]);
                tmp=findobj('Tag','dataYlim');
                tmp.String=num2str([min(obj.dataYaxis),max(obj.dataYaxis)]);
                ChannelPositionindex=currentresult.Spectrogram.get('channelindexplot');
         end
         [~,Channelindex]=ismember(currentresult.LFPinfo.channelselect(ChannelPositionindex),obj.ChannelPosition(:,1));
         obj.ChannelPosition=obj.ChannelPosition(Channelindex,:);
     end
     function openEEGParameters(obj)   
        dlg = dialog('Name', 'Topoplot Parameters', ...
                'Position', [100, 100, 400, 400]);
            
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 350, 150, 25], ...
                'String', '绘图半径:', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 350, 100, 25], ...
                'String', num2str(obj.Parameters.plotrad), ...
                'Callback', @(src,~) obj.updateParameters('plotrad', str2double(src.String)));
            
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 310, 150, 25], ...
                'String', '等高线数量:', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 310, 100, 25], ...
                'String', num2str(obj.Parameters.numcontour), ...
                'Callback', @(src,~) obj.updateParameters('numcontour', str2double(src.String)));
            
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 270, 150, 25], ...
                'String', '网格缩放:', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 270, 100, 25], ...
                'String', num2str(obj.Parameters.gridscale), ...
                'Callback', @(src,~) obj.updateParameters('gridscale', str2double(src.String)));
            
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 230, 150, 25], ...
                'String', '绘图样式:', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'popupmenu', ...
                'Position', [180, 230, 100, 25], ...
                'String', {'contour', 'fill', 'both'}, ...
                'Value', find(strcmp({'contour', 'fill', 'both'}, obj.Parameters.style)), ...
                'Callback', @(src,~) obj.updateParameters('style', src.String));
           
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 230, 150, 25], ...
                'String', 'head mode:', ...
                'HorizontalAlignment', 'right'); 
            
            uicontrol('Parent', dlg, ...
                'Style', 'popupmenu', ...
                'Position', [180, 230, 100, 25], ...
                'String', {'human', 'rodent'}, ...
                'Value', find(strcmp({'human', 'rodent'}, obj.Parameters.headmode)), ...
                'Callback', @(src,~) obj.updateParameters('headmode', src.String));

            % 确定按钮
            uicontrol('Parent', dlg, ...
                'Style', 'pushbutton', ...
                'String', '确定', ...
                'Position', [150, 30, 100, 30], ...
                'Callback', @(~,~) delete(dlg));
     end
     function openCSDParameters(obj)
                       % 打开CSD参数设置对话框
            dlg = dialog('Name', 'CSD参数设置', ...
                'Position', [100, 100, 500, 600]);
            
            % 基础参数
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 560, 150, 25], ...
                'String', '基函数类型:', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'popupmenu', ...
                'Position', [180, 560, 150, 25], ...
                'String', {'gauss', 'step', 'gauss_lim'}, ...
                'Value', find(strcmp({'gauss', 'step', 'gauss_lim'}, obj.Parameters.src_type)), ...
                'Callback', @(src,~) obj.updateParameters('src_type', src.String{src.Value}));
            
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 520, 150, 25], ...
                'String', '电导率 sigma (S/m):', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 520, 100, 25], ...
                'String', num2str(obj.Parameters.sigma), ...
                'Callback', @(src,~) obj.updateParameters('sigma', str2double(src.String)));
            
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 480, 150, 25], ...
                'String', '组织厚度 h (mm):', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 480, 100, 25], ...
                'String', num2str(obj.Parameters.h), ...
                'Callback', @(src,~) obj.updateParameters('h', str2double(src.String)));
            
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 440, 150, 25], ...
                'String', '初始源数量:', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 440, 100, 25], ...
                'String', num2str(obj.Parameters.n_src_init), ...
                'Callback', @(src,~) obj.updateParameters('n_src_init', round(str2double(src.String))));
            
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 400, 150, 25], ...
                'String', '基函数宽度 R_init (mm):', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 400, 100, 25], ...
                'String', num2str(obj.Parameters.R_init), ...
                'Callback', @(src,~) obj.updateParameters('R_init', str2double(src.String)));
            
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 360, 150, 25], ...
                'String', '正则化参数 lambda:', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 360, 100, 25], ...
                'String', num2str(obj.Parameters.lambd), ...
                'Callback', @(src,~) obj.updateParameters('lambd', str2double(src.String)));
            
            % 网格参数
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 320, 150, 25], ...
                'String', 'X方向扩展 ext_x (mm):', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 320, 100, 25], ...
                'String', num2str(obj.Parameters.ext_x), ...
                'Callback', @(src,~) obj.updateParameters('ext_x', str2double(src.String)));
            
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 280, 150, 25], ...
                'String', 'Y方向扩展 ext_y (mm):', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 280, 100, 25], ...
                'String', num2str(obj.Parameters.ext_y), ...
                'Callback', @(src,~) obj.updateParameters('ext_y', str2double(src.String)));
            
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 240, 150, 25], ...
                'String', 'X方向网格密度 gdx (mm):', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 240, 100, 25], ...
                'String', num2str(obj.Parameters.gdx), ...
                'Callback', @(src,~) obj.updateParameters('gdx', str2double(src.String)));
            
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 200, 150, 25], ...
                'String', 'Y方向网格密度 gdy (mm):', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 200, 100, 25], ...
                'String', num2str(obj.Parameters.gdy), ...
                'Callback', @(src,~) obj.updateParameters('gdy', str2double(src.String)));
            
            % 高级参数
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 160, 150, 25], ...
                'String', '距离表密度:', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 160, 100, 25], ...
                'String', num2str(obj.Parameters.dist_table_density), ...
                'Callback', @(src,~) obj.updateParameters('dist_table_density', round(str2double(src.String))));
            
            % Method of Images参数 (用于MEA)
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 120, 150, 25], ...
                'String', 'MoI迭代次数:', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 120, 100, 25], ...
                'String', num2str(obj.Parameters.MoI_iters), ...
                'Callback', @(src,~) obj.updateParameters('MoI_iters', round(str2double(src.String))));
            
            uicontrol('Parent', dlg, ...
                'Style', 'text', ...
                'Position', [20, 80, 150, 25], ...
                'String', '生理盐水电导率 sigma_S:', ...
                'HorizontalAlignment', 'right');
            
            uicontrol('Parent', dlg, ...
                'Style', 'edit', ...
                'Position', [180, 80, 100, 25], ...
                'String', num2str(obj.Parameters.sigma_S), ...
                'Callback', @(src,~) obj.updateParameters('sigma_S', str2double(src.String)));
            
            % 优化选项
            uicontrol('Parent', dlg, ...
                'Style', 'checkbox', ...
                'Position', [180, 40, 150, 25], ...
                'String', '交叉验证', ...
                'Value', obj.Parameters.cross_validate, ...
                'Callback', @(src,~) obj.updateParameters('cross_validate', logical(src.Value)));
            
            uicontrol('Parent', dlg, ...
                'Style', 'checkbox', ...
                'Position', [320, 40, 150, 25], ...
                'String', 'L-curve优化', ...
                'Value', obj.Parameters.l_curve, ...
                'Callback', @(src,~) obj.updateParameters('l_curve', logical(src.Value)));

            % 确定按钮
            uicontrol('Parent', dlg, ...
                'Style', 'pushbutton', ...
                'String', '确定', ...
                'Position', [200, 10, 100, 25], ...
                'Callback', @(~,~) delete(dlg));
        end
        
     function calculateSourceDistribution(obj)
            % 计算源分布         
            if isempty(obj.Data) || isempty(obj.ChannelPosition)
                error('没有可用的数据或通道位置信息');
            end 
            try
                obj.ChooseDatatype();
            end
            xlim=findobj(obj,'Tag','dataXlim');
            xlim=str2num(xlim.String);
            if ~isempty(obj.dataYaxis)
                ylim=findobj(obj,'Tag','dataYlim');
                ylim=str2num(ylim.String);
                data=squeeze(mean(obj.Data(obj.dataXaxis>=xlim(1)&obj.dataXaxis<=xlim(2),obj.dataYaxis>ylim(1)&obj.dataYaxis<ylim(2),:,:),[2,4]));
            else
                data=squeeze(mean(obj.Data(obj.dataXaxis>=xlim(1)&obj.dataXaxis<=xlim(2),:,:),3));
            end
            parameters=obj.Parameters;
            delete(findobj('Parent',obj.figurepanel));
            switch obj.ChannelType
                case 'CSD'
                    obj.Source=obj.calculateCSD(data,parameters);
                    if isfield(obj.Source,'csd_x')&& isfield(obj.Source,'csd_y') 
                        obj.figurepanel.create([],'SourceDistribution','imagesc3D');
                        obj.figurepanel.plot(obj.dataXaxis,obj.Source.csd_x(1,:),obj.Source.csd_y(:,1),obj.Source.CSD);
                    elseif isfield(obj.Source,'csd_x')
                        obj.figurepanel.create([],'SourceDistribution','imagesc-scroll');
                        obj.figurepanel.plot(obj.dataXaxis,obj.Source.csd_x,obj.Source.CSD);
                    elseif isfield(obj.Source,'csd_y')
                        obj.figurepanel.create([],'SourceDistribution','imagesc-scroll');
                        obj.figurepanel.plot(obj.dataXaxis,obj.Source.csd_y,obj.Source.CSD);
                    end
                case 'EEG'
                    [~, sourcedata,grid,xmesh,ymesh]=obj.calculateTopo(data,parameters);
                    obj.Source=sourcedata;
                    obj.grid=grid;
                    obj.xmesh=xmesh;
                    obj.ymesh=ymesh;
            end
     end
     function Source=calculateCSD(obj,data,parameters)
         Source=get_kCSD(obj.ChannelPosition(:,2:3),data',parameters);
         % CSD is a time*x*y matrix (2d CSD) or time*x matrix (1d CSD) 
     end
     function [sourcedata,grid,xmesh,ymesh]=calculateTopo(obj,data,parameters)
         % on working ,using eeglab topoplot
         
     end
      function updateParameters(obj, paramName, value)
            % 更新算法参数
            if isfield(obj.Parameters, paramName)
                obj.Parameters.(paramName) = value;
            else
                error('参数 %s 不存在', paramName);
            end
      end
end

methods(Static)
    function obj=create(parent,varargin)
            % create a panel in the parent from a neuroresult
           if isempty(parent)
                parent=figure;
            end
            p=inputParser;
            addParameter(p,'Data',[],@isnumeric);% 2-D ,with 1-D as position;
            addParameter(p,'ChannelPosition',[],@(x) isstruct(x)||@(x) isnumeric(x));
            parse(p);
            if isempty(p.Results.ChannelPosition)
                global currentresult
                if isfield(currentresult.ChannelTag,'ChannelPosition')
                    ChannelPosition=currentresult.ChannelTag.ChannelPosition;
                else
                    error('No channel position was detected!');
                end
            end
            obj=NeuroPlot.SourceDistribution('Parent',parent);
            
            if isstruct(ChannelPosition) % EEG format
                obj.ChannelType='EEG';
                obj.Parameters=obj.DEFAULT_EEG_PARAMS;
                obj.ChannelPosition=ChannelPosition;% not worked yet, string should be char.
                   
            else % channelindex,channelposition(x,y),channelshank
                obj.ChannelType='CSD';
                obj.Parameters=obj.DEFAULT_CSD_PARAMS;
                obj.ChannelPosition=ChannelPosition;
                           
            end
            obj.createToolbar();
            if isempty(p.Results.Data)
                warning('load Data from the panel');
                obj.createDataLoadPanel();
            else
                obj.Data=Data;
            end
            obj.figurepanel=NeuroPlot.figurecontrol('Parent',obj);
           
            set(obj,'Heights',[-1,-1,-8]);
            
    end
    
end
end












